# Generated by Django 5.1.6 on 2025-05-20 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('description', models.TextField(verbose_name='Kategori Açıklaması')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Kategori İkonu')),
            ],
            options={
                'verbose_name': 'Eşya Kategorisi',
                'verbose_name_plural': 'Eşya Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Eşya Adı')),
                ('description', models.TextField(verbose_name='Eşya Açıklaması')),
                ('found_date', models.DateField(verbose_name='Bulunma Tarihi')),
                ('found_location', models.CharField(max_length=200, verbose_name='Bulunduğu Yer')),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/', verbose_name='Eşya Resmi')),
                ('status', models.CharField(choices=[('available', 'Mevcut'), ('claimed', 'Talep Edildi')], default='available', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bulan Kişi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Bulunan Eşya',
                'verbose_name_plural': 'Bulunan Eşyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Eşya Adı')),
                ('description', models.TextField(verbose_name='Eşya Açıklaması')),
                ('lost_date', models.DateField(verbose_name='Kaybolma Tarihi')),
                ('lost_location', models.CharField(max_length=200, verbose_name='Kaybolduğu Yer')),
                ('contact_info', models.CharField(max_length=100, verbose_name='İletişim Bilgisi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/', verbose_name='Eşya Resmi')),
                ('status', models.CharField(choices=[('lost', 'Kayıp'), ('found', 'Bulundu'), ('claimed', 'Talep Edildi')], default='lost', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory', verbose_name='Kategori')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bildiren Kişi')),
            ],
            options={
                'verbose_name': 'Kayıp Eşya',
                'verbose_name_plural': 'Kayıp Eşyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('claim_description', models.TextField(verbose_name='Talep Açıklaması')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=10, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Yönetici Notları')),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
                ('found_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.founditem', verbose_name='Bulunan Eşya')),
                ('lost_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.lostitem', verbose_name='Kayıp Eşya')),
            ],
            options={
                'verbose_name': 'Talep',
                'verbose_name_plural': 'Talepler',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('regular', 'Normal Kullanıcı'), ('staff', 'Personel'), ('admin', 'Yönetici')], default='regular', max_length=10, verbose_name='Kullanıcı Tipi')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Bölüm/Departman')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
