# Generated by Django 5.1.6 on 2025-05-26 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='solved_by_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.claim', verbose_name='Çözümleyen Talep'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='solved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Çözümlenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('available', 'Mevcut'), ('claimed', 'Sahibi Bulundu')], default='available', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('lost', 'Kayıp'), ('found', 'Bulundu'), ('solved', 'Çözümlendi')], default='lost', max_length=10, verbose_name='Durum'),
        ),
    ]
