# Generated by Django 5.1.6 on 2025-05-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_lostitem_solved_by_claim_lostitem_solved_date_and_more'),
    ]

    operations = [
    ]
