# Generated by Django 5.1.6 on 2025-05-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_founditem_solved_by_claim_founditem_solved_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='found_location',
        ),
    ]
