# Generated by Django 5.1.6 on 2025-05-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('available', 'Mevcut'), ('claimed', 'Sahip Bulundu'), ('solved', 'Çözümlendi')], default='available', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('lost', 'Kayıp'), ('claimed', 'Bulundu'), ('solved', 'Çözümlendi')], default='lost', max_length=10, verbose_name='Durum'),
        ),
    ]
